function [grad] = calc_AB_grad(order, p)
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here
    rx = p(1);
    ry = p(2);
    rz = p(3);

    if(order == 2)
        grad = zeros(3, 3, 15);
        % first three pages are all zeros
        grad(:, :, 4) = [zeros(1, 3); ...
                         0 0 1;...
                         0 1 0];
        grad(:, :, 5) = [zeros(1, 3); ...
                         0 2 0;...
                         0 0 -2];
        grad(:, :, 6) = [0 0 1;...
                         zeros(1, 3); ...
                         1 0 0];    
        grad(:, :, 7) = [0 1 0;...
                         1 0 0;
                         zeros(1, 3)];                           
        grad(:, :, 8) = [2 0 0;...  
                         zeros(1, 3);
                         0 0 -2];  
        grad(:, :, 9) = [zeros(1, 3);...
                         0 2*rz 2*ry;
                         0 2*ry -2*rz];
        grad(:, :, 10) = [zeros(1, 3);...
                          0 6*ry -6*rz;
                          0 -6*rz -6*ry];
        grad(:, :, 11) = [0 rz ry;...
                         rz 0 rx;
                         ry rx 0];        
        grad(:, :, 12) = [0 2*ry -2*rz;...
                          2*ry 2*rx 0; ...
                         -2*rz 0    -2*rx];
        grad(:, :, 13) = [2*rz 0 2*rx; ...
                          zeros(1, 3);...
                          2*rx 0 -2*rz];
        grad(:, :, 14) = [2*ry 2*rx 0;  ...
                          2*rx 0 -2*rz; ...
                          0   -2*rz -2*ry];  
        grad(:, :, 15) = [6*rx 0  -6*rz;...
                          zeros(1, 3);...
                          -6*rz 0  -6*rx;];                         
    end
end

